### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by gskorupa** [gskorupa/Cricket#225]
```
java.lang.NullPointerException
	at org.cricketmsf.microsite.in.http.ContentRequestProcessor.processGetPublished(ContentRequestProcessor.java:78)
	at org.cricketmsf.services.Microsite.getPublishedContent(Microsite.java:341)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.cricketmsf.Kernel.getEventProcessingResult(Kernel.java:199)
	at org.cricketmsf.Kernel.getEventProcessingResult(Kernel.java:217)
	at org.cricketmsf.services.Microsite.contentGetPublished(Microsite.java:335)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.cricketmsf.in.http.HttpAdapter.createResponse(HttpAdapter.java:386)
	at org.cricketmsf.in.http.HttpAdapter.doHandle(HttpAdapter.java:152)
	at org.cricketmsf.in.http.HttpAdapter.lambda$handle$0(HttpAdapter.java:129)
	at java.base/java.lang.Thread.run(Thread.java:830)
FINE:2020-03-06 00:11:16 +0000: 1583452961417:HttpAdapter:sending request to hook method contentGetPublished
```

**Comment by gskorupa** [comment]
The reason was the disappearing request parameters. Resolved by removing the creation of an additional (unnecessary) thread.
